version: '3.7'
services:
  web:
    image: nginx:alpine
    volumes:
        - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./web:/var/www/html"
        - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    environment:
      - NGINX_HOST=localhost
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
        - "8080:80"
    restart: always
    depends_on:
        - php
        - db
  php:
    image: 'php:fpm'
    restart: always
    volumes:
        - "./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        - "./web:/var/www/html"
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: shisha_db
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - "./data/db/mysql:/var/lib/mysql"
    networks:
      - default
    ports: 
      - "3306:3306"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    restart: always